### ISSUE TITLE
default mumble-server.ini

### ISSUE THREAD

**Issue by mrbreil** [PhasecoreX/docker-mumble-server-ldap#19]
It's not really an issue, but for people new to mumble like me it's frustrating because your default file contains a tiny error.

Shouldn't the part with `#ice="tcp -h 127.0.0.1 -p 6502"` be commented out? It took me a while to figure that out. Or does it have a purpose that I don't understand?

**Comment by PhasecoreX** [comment]
Unless I am misunderstanding you, that line is commented out. It starts with a `#`, which means it is commented out.

**Comment by mrbreil** [comment]
sorry google translate.
This line should NOT be commented out, right?

**Comment by PhasecoreX** [comment]
Wow, yeah that is weird, it is supposed to be uncommented. I'm not sure how I missed that. I checked my local config and it is uncommented there. And unsurprisingly, commenting it makes the LDAPAuth not work. Thanks for the heads up! I have updated it here.
